image: barichello/sfml:latest

variables:
  GAME_NAME: multicaster

stages:
  - build
  - package

linux-build:
  stage: build
  script:
    - scons
  artifacts:
    paths:
      - bin

linux-zip:
  stage: package
  script:
    - mkdir bin/lib
    - cp /usr/lib/x86_64-linux-gnu/libsfml-*.so.* bin/lib
    - mv bin $GAME_NAME
  artifacts:
    name: $GAME_NAME-linux
    paths:
      - $GAME_NAME
  dependencies:
    - linux-build
